export const menuItemsData = [
  {
    id: 1,
    name: 'Ring',
    info: ' gold plated ring with crystal design',
    price: 25,
    img: '/images/I1.webp',
  },
  {
    id: 2,
    name: 'Ring',
    info: ' gold plated ring with crystal design',
    price: 25,
    img: '/images/I2.webp',
  },
  {
    id: 3,
    name: 'Ring',
    info: ' gold plated ring with crystal design',
    price: 25,
    img: '/images/I3.webp',
  },
  {
    id: 4,
    name: 'Ring',
    info: ' gold plated ring with crystal design',
    price: 25,
    img: '/images/I4.webp',
  },
  {
    id: 5,
    name: 'Ring',
    info: ' gold plated ring with crystal design',
    price: 25,
    img: '/images/I5.webp',
  },
  {
    id: 6,
    name: 'Earring',
    info: 'earrings with textured link design in gold tone',
    price: 25,
    img: '/images/I6.webp',
  },
  {
    id: 7,
    name: 'Earring',
    info: 'earrings with textured link design in gold tone',
    price: 25,
    img: '/images/I7.jpeg',
  },
  {
    id: 8,
    name: 'Earring',
    info: 'earrings with textured link design in gold tone',
    price: 25,
    img: '/images/I8.webp',
  },
  {
    id: 9,
    name: 'Earring',
    info: 'earrings with textured link design in gold tone',
    price: 25,
    img: '/images/I9.webp',
  },
  {
    id: 10,
    name: 'Earring',
    info: 'earrings with textured link design in gold tone',
    price: 25,
    img: '/images/I10.jpeg',
  },
  {
    id: 11,
    name: 'Bracelet',
    info: 'Curve bangle bracelet in minimal design in gold tone',
    price: 25,
    img: '/images/I11.jpg',
  },
 
  {
    id: 13,
    name: 'Bracelet',
    info: 'Curve bangle bracelet in minimal design in gold tone',
    price: 25,
    img: '/images/I13.jpeg',
  },
  {
    id: 14,
    name: 'Bracelet',
    info: 'Curve bangle bracelet in minimal design in gold tone',
    price: 25,
    img: '/images/I14.jpeg',
  },
  {
    id: 15,
    name: 'Bracelet',
    info: 'Curve bangle bracelet in minimal design in gold tone',
    price: 25,
    img: '/images/I15.jpeg',
  },
  {
    id: 16,
    name: 'Bracelet',
    info: ' Curve bangle bracelet in minimal design in gold tone',
    price: 25,
    img: '/images/I12.jpg',
  },
  {
    id: 17,
    name: 'Gold',
    info: 'Topshop celestial  necklace in gold',
    price: 25,
    img: '/images/I17.webp',
  },
  {
    id: 18,
    name: 'Gold',
    info: 'Topshop celestial  necklace in gold',
    price: 25,
    img: '/images/I18.jpg',
  },
  {
    id: 19,
    name: 'Gold',
    info: 'Topshop celestial  necklace in gold',
    price: 25,
    img: '/images/I19.png',
  },
  {
    id: 20,
    name: 'Gold',
    info: 'Topshop celestial  necklace in gold',
    price: 25,
    img: '/images/I20.webp',
  },
  {
    id: 21,
    name: 'Gold',
    info: 'Topshop celestial  necklace in gold',
    price: 25,
    img: '/images/I21.png',
  },

];
